site_name: EpiMetal documentation
pages:
 - Home: index.md
 - User guide: userguide.md
 - Installation: installation.md
 - License: license.md
theme: 'material'
markdown_extensions:
    - toc:
        permalink: true