web:
 build: ./
 command: "nginx"
 volumes:
  - ./src:/plotter/src
 ports:
  - "30303:80"
 links:
  - api

api:
 build: ./python-api
 command: "/run.sh load"
 volumes:
  - /var/log/api
 expose:
  - "8080"
 links:
  - db

mongodata:  
  image: mongo:latest
  volumes:
    - /data/db
  command: --break-mongo

db:
 image: mongo:latest
 volumes_from:
  - mongodata
 command: --smallfiles


